config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :offers
  resources :sells, :controller => 'offers', :type => 'Sell'
  resources :rents, :controller => 'offers', :type => 'Rent'
  resources :swaps, :controller => 'offers', :type => 'Swap'

  resources :properties
  resources :users

  get '/login', :to => 'user_sessions#new', :as => :new_user_session
  post '/login', :to => 'user_sessions#create', :as => :user_sessions
  get '/logout', :to => 'user_sessions#destroy', :as => :user_session

  get '/disclaimer', :to => 'pages#disclaimer', :as => :disclaimer
  get '/contacts', :to => 'pages#contacts', :as => :contacts
  post '/contacts', :to => 'feedbacks#create', :as => :feedbacks
  post '/message', :to => 'contact_messages#create', :as => :contact_messages
  get '/privacy_policy', :to => 'pages#privacy_policy', :as => :privacy_policy
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_authentic { |u| u.maintain_sessions = false }

  has_many :properties
  has_many :offers, :through => :properties

  belongs_to :company
  accepts_nested_attributes_for :company

  before_validation :set_password, :if => :new_record?
  after_commit :send_welcome_email

  private

  def set_password
    @password = SecureRandom.base64(8)
    @new_user = true

    self.password = @password
    self.password_confirmation = @password
  end

  def send_welcome_email
    return unless @new_user

    SendPasswordJob.perform_later(self, @password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :resource_user

  def new
    @resource_user = User.new
    @resource_user.build_company
  end

  def create
    @resource_user = User.new(user_params)

    if @resource_user.save
      redirect_to new_user_path, :notice => 'Registration successful. Check mail for password!'
    else
      flash.now[:error] = 'User not created'
      render :new
    end
  end

  def edit
    @resource_user = current_user
  end

  def update
    @resource_user = current_user

    if @resource_user.update_attributes(user_params)
      flash[:notice] = 'Successfully updated profile'
      redirect_to root_url
    else
      render :action => 'edit'
    end
  end

  private

  def resource_user
    @resource_user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name,
                                 :address,
                                 :email,
                                 :phone_number,
                                 :password,
                                 :password_confirmation,
                                 :company_attributes => [:name, :abn, :abn_confirm])
  end
end

app/views/users/_company_fields.html.slim
= f.fields_for :company do |ff|
  .abn-group@@company_fields
    .form-group.row class="#{'invisible' if resource_user.company.abn.present?}"
      .col-2.checkbox
        = label_tag do
          => ff.check_box :abn_confirm, {:checked => resource_user.company.abn.present? || resource_user.company.abn_confirm == 'true', :'data-role' => 'abn_confirm'}, true, false
          span I have ABN
      .col-10 If you are listing more than 1 property or are a real estate professional or agent you must provide an ABN.

    .company_fields@company_fields class="#{'invisible' unless resource_user.company.try(:abn).present? || resource_user.company.try(:abn_confirm) == 'true'}"
      .form-group.row
        .col-2
          = ff.label :abn, 'ABN'
        .col-10
          - if resource_user.company.abn_valid?
            = text_field_tag 'abn', resource_user.company.abn
          - else
            = ff.text_field :abn, :class => 'form-control'
          - if controller.action_name == 'edit' && resource_user.company.abn.present?
            span = resource_user.company.abn_valid? ? 'Valid' : 'Not Valid'
          .error-msg = resource_user.errors['company.abn'].join(', ')

      .form-group.row
        .col-2
          = ff.label :name, 'Company name'
        .col-10
          = ff.text_field :name, :class => 'form-control'
          .error-msg = resource_user.errors['company.name'].join(', ')

app/views/users/edit.html.slim
ul.nav.nav-tabs.profile role="tablist"
  li class="nav-item"
    a.nav-link class="#{'active' if params[:tab].blank?}" data-toggle="tab" href="#profile" role="tab" Edit Profile
  li class="nav-item"
    a.nav-link class="#{'active' if params[:tab] == 'offers'}" data-toggle="tab" href="#offers" role="tab" My Offers

.tab-content
  .tab-pane class="#{'active' if params[:tab].blank?}" id="profile" role="tabpanel"
    .user_edit
      = form_for @resource_user, :method => :patch do |f|
        .form-group.row
          .col-2
            = f.label :name
          .col-4
            = f.text_field :name, :class => 'form-control'
          .error-msg = resource_user.errors[:name].join(', ')

        .form-group.row
          .col-2
            = f.label :address
          .col-4
            = f.text_field :address, :class => 'form-control'
          .error-msg = resource_user.errors[:address].join(', ')

        .form-group.row
          .col-2
            = f.label :email
          .col-4
            = f.text_field :email, :class => 'form-control'
          .error-msg = resource_user.errors[:email].join(', ')

        .form-group.row
          .col-2
            = f.label :phone_number
          .col-4
            = f.text_field :phone_number, :class => 'form-control'
          .error-msg = resource_user.errors[:phone_number].join(', ')

        .form-group.row
          .col-2
            = f.label :password
          .col-4
            = f.password_field :password, :class => 'form-control'
          .error-msg = resource_user.errors[:password].join(', ')

        .form-group.row
          .col-2
            = f.label :password_confirmation
          .col-4
            = f.password_field :password_confirmation, :class => 'form-control'
          .error-msg = resource_user.errors[:password_confirmation].join(', ')

        = render 'company_fields', :f => f, :resource_user => @resource_user

        .form-group.row
          .col-2
          .col-4
            = f.submit 'Update', :class => "btn btn-primary btn-md"
  .tab-pane class="#{'active' if params[:tab] == 'offers'}" id="offers" role="tabpanel"
    .offers.row
      .col-md-8
        - current_user.offers.each do |offer|
          a.list-group-item.list-group-item-action href="#{offer_path(offer)}"
            .offer.d-flex.flex-row
              - if offer.property_gallery.try(:images).present?
                .offer-image.m-1 style="background-image:url(#{offer.property_gallery.images.first.url(:index_preview)});"
              - else
                / .offer-image.m-1 = image_tag 'default_property_image'
              .offer-info-left.m-1
                .h5 = offer.property.property_type
                p = offer.property.address
                ul.list-group.params
                  - if offer.property.try(:bedrooms).try(:positive?)
                    li.list-group-item.justify-content-between
                      | Bedrooms
                      span.badge.badge-default.badge-pill = offer.property.bedrooms
                  - if offer.property.try(:bathrooms).try(:positive?)
                    li.list-group-item.justify-content-between
                      | Bathrooms
                      span.badge.badge-default.badge-pill = offer.property.bathrooms
                  - if offer.property.try(:car_spaces).try(:positive?)
                    li.list-group-item.justify-content-between
                      | Car spaces
                      span.badge.badge-default.badge-pill = offer.property.car_spaces
                ul.list-group.area
                  - if offer.property.try(:floor_area).try(:positive?)
                    li.list-group-item
                      = "Floor area: #{offer.property.floor_area}"
                      span m<sup>2</sup>
                  - if offer.property.try(:land_area).try(:positive?)
                    li.list-group-item
                      = "Land area: #{offer.property.land_area}"
                      span m<sup>2</sup>
              .offer-info-right.m-1
                span.badge.badge-info.badge-pill = offer.user.try(:company).try(:abn_valid?) ? 'real estate agent' : 'private property owner'
                - if offer.type == 'Swap'
                  p = "#{offer.type}"
                - else
                  - if current_user
                    p = "#{offer.type} for"
                    p = number_to_currency(offer.price, :unit => 'AUD', :precision => 0, :delimiter => ',', :format => '%n %u')
                  - else
                    p = "#{offer.type}"
                - if offer.with_period?
                  p.p-1
                    = "Period: #{offer.period}"
      .col-md-4

app/views/users/new.html.slim
.page-header
  .h1 Registration
  hr
.user_new
  = form_for @resource_user, :method => :post do |f|
    .form-group.row.email
      .col-2
        = f.label :email
      .col-10
        = f.text_field :email, :class => 'form-control'
        .error-msg = resource_user.errors[:email].join(', ')

    .form-group.row
      .col-2
      .col-10 Your password has been sent to your email in box.

    = render 'company_fields', :f => f, :resource_user => @resource_user

    .form-group.row
      .col-2
      .col-4
        = f.submit 'Become a Member', :class => "btn btn-primary btn-md"