config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :offers
  resources :sells, :controller => 'offers', :type => 'Sell'
  resources :rents, :controller => 'offers', :type => 'Rent'
  resources :swaps, :controller => 'offers', :type => 'Swap'

  resources :properties
  resources :users

  get '/login', :to => 'user_sessions#new', :as => :new_user_session
  post '/login', :to => 'user_sessions#create', :as => :user_sessions
  get '/logout', :to => 'user_sessions#destroy', :as => :user_session

  get '/disclaimer', :to => 'pages#disclaimer', :as => :disclaimer
  get '/contacts', :to => 'pages#contacts', :as => :contacts
  post '/contacts', :to => 'feedbacks#create', :as => :feedbacks
  post '/message', :to => 'contact_messages#create', :as => :contact_messages
  get '/privacy_policy', :to => 'pages#privacy_policy', :as => :privacy_policy
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @main_page_sell_offers = Sell.order(:created_at => :asc).last 3
    @main_page_rent_offers = Rent.order(:created_at => :desc).last 3
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.slim
.index.row
  .col-md-12
    .h4 Save tens of thousands of dollars, don’t pay sales commission don’t pay agent marketing fees!

  .col-2
    .h2
      = link_to 'SELL', offers_path(:type => 'Sell')
  .col-10
    .h3 properties for sale
  .col-2
    .h2
      = link_to 'SWAP', offers_path(:type => 'Swap')
  .col-10
    .h3 properties to swap
  .col-2
    .h2
      = link_to 'RENT', offers_path(:type => 'Rent')
  .col-10
    .h3 properties for rent
  - if current_user
    .col-2
      .h2
        = link_to 'LIST', edit_user_path(current_user, :tab => 'offers')
    .col-10
      .h3 list my property
  .col-2
    .h2
      = link_to 'SEARCH', offers_path
  .col-10
    .h3 I am looking for a property

  .col-md-6
    h3 NO SALES COMMISSIONS TO PAY
  .col-md-6
    h3 NO AGENT MARKETING FEES TO PAY