config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :offers
  resources :sells, :controller => 'offers', :type => 'Sell'
  resources :rents, :controller => 'offers', :type => 'Rent'
  resources :swaps, :controller => 'offers', :type => 'Swap'

  resources :properties
  resources :users

  get '/login', :to => 'user_sessions#new', :as => :new_user_session
  post '/login', :to => 'user_sessions#create', :as => :user_sessions
  get '/logout', :to => 'user_sessions#destroy', :as => :user_session

  get '/disclaimer', :to => 'pages#disclaimer', :as => :disclaimer
  get '/contacts', :to => 'pages#contacts', :as => :contacts
  post '/contacts', :to => 'feedbacks#create', :as => :feedbacks
  post '/message', :to => 'contact_messages#create', :as => :contact_messages
  get '/privacy_policy', :to => 'pages#privacy_policy', :as => :privacy_policy
end

app/models/offer.rb
class Offer < ApplicationRecord
  OFFER_TYPES = %w(Sell Rent Swap).freeze
  PERIOD_TYPES = %w(Daterange Week Month Year Flexible Permanently Other).freeze

  belongs_to :property
  accepts_nested_attributes_for :property

  has_one :property_gallery, :through => :property
  has_one :user, :through => :property

  validates :description, :presence => true
  validates :period, :presence => true, :if => :with_period?

  def with_period?
    OFFER_TYPES[1..2].include? type
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  helper_method :resource_offer

  def index
    @offers =
      ::SearchService.new.call(params).paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @resource_offer = offer_klass.new
    property = @resource_offer.build_property
    user = property.build_user
    user.build_company
    property.build_property_gallery
  end

  def create
    @resource_offer = offer_klass.new(offer_params)
    @resource_offer.status = 'new' # временно пока не запилю стейт машину
    @resource_offer.user = current_user if current_user

    if @resource_offer.save
      redirect_to offer_path(@resource_offer), :notice => 'Offer created'
    else
      flash.now[:error] = 'Offer not created'
      render :new
    end
  end

  def edit; end

  def update
    if resource_offer.update_attributes(offer_params)
      redirect_to offer_path(resource_offer), :notice => 'Offer updated'
    else
      flash.now[:error] = 'Offer not updated'
      render(:edit)
    end
  end

  def show; end
end

private

def resource_offer
  @resource_offer ||= Offer.find(params[:id])
end

def offer_params # rubocop:disable MethodLength
  params.require(offer_klass.name.underscore.to_sym)
        .permit(
          :description,
          :price,
          :status,
          :period,
          :type,
          :rent_confirm,
          :rent_period,
          :rent_price,
          :property_attributes => [:id,
                                   :address,
                                   :bedrooms,
                                   :bathrooms,
                                   :car_spaces,
                                   :land_area,
                                   :floor_area,
                                   :latitude,
                                   :longitude,
                                   :property_type,
                                   :lounge_room,
                                   :kitchen,
                                   :dinning_room,
                                   :laundry,
                                   :on_sweet,
                                   :powder_room,
                                   :property_gallery_attributes => [{ :images => [] }],
                                   :user_attributes => [:email,
                                                        :company_attributes =>
                                                          [:abn_confirm, :abn, :name]]]
        )
end

def offer_klass
  raise unless params[:type].in? ::Offer::OFFER_TYPES
  params[:type].constantize
end

app/views/offers/_form.html.slim
.page-header
  .h1 = "For #{resource_offer.type}"
  hr
.offer_form@@offer_form data-country=Rails.application.secrets[:location]['country'] data-region=Rails.application.secrets[:location]['region']
  = form_for resource_offer,
             :url => (resource_offer.new_record? ? offers_url(:type => resource_offer.type) : offer_url(resource_offer, :type => resource_offer.type)),
             :method => (resource_offer.new_record? ? :post : :patch) do |f|
    - if resource_offer.with_period?
      .form-group.row
        .col-2
          = f.label :period, :class => 'col-form-label'
        .col-10
          = select_tag 'period', options_for_select(Offer::PERIOD_TYPES), :class => 'custom-select', :'data-role' => 'period_select', :include_blank => "Select #{resource_offer.type.downcase} period"
          = f.hidden_field :period, :'data-role' => 'period_input'
          .error-msg = resource_offer.errors[:period].join(', ')
      .form-group.row
        .col-2
        .col-10
          .invisible@quantity_field
            = number_field_tag 'quantity', 1, :in => 1...13, :class => 'form-control quantity-input', :'data-role' => 'quantity_input'
          .invisible@daterange_field
            = text_field_tag 'daterange', nil, :maxlength => 23, :class => 'daterange-input form-control', :'data-role' => 'daterange_input'

    - unless resource_offer.type == 'Swap'
      .form-group.row
        .col-2
          = f.label :price, :class => 'col-form-label'
        .col-10
          = f.text_field :price, :class => 'form-control price-input'
          span.unit AUD
          .error-msg = resource_offer.errors[:price].join(', ')

    = f.fields_for :property do |ff|
      .gmap-group@gmap_group
        .form-group.row
          .col-2
            = ff.label :address, :class => 'col-form-label'
          .col-5
            = ff.text_field :address, :'data-role' => 'gmaps_input_address', :placeholder => 'Start typing a place...', :class => 'form-control'
            = ff.hidden_field :latitude, :'data-role' => 'gmaps_output_latitude'
            = ff.hidden_field :longitude, :'data-role' => 'gmaps_output_longitude'
            .gmap-error@gmaps_error
            .error-msg = resource_offer.errors[:"property.address"].join(', ')

        .form-group
          .gmap@gmaps_canvas

    .form-group.row
      .col-2
        = f.label :description, :class => 'col-form-label'
      .col-10
        = f.text_area :description, :rows => 5, :class => 'form-control'
        .error-msg = resource_offer.errors[:description].join(', ')

    .h4 Property parameters
    hr

    = f.fields_for :property do |ff|
      .form-group.row.property-type
        .col-2
          = ff.label :property_type, :class => 'col-form-label'
        .col-10
          = select_tag 'property_type', grouped_options_for_select(Property::PROPERTY_TYPES, nil, divider: ''), :class => 'custom-select', :'data-role' => 'property_type_select', :include_blank => 'Select property type'
          = ff.hidden_field :property_type, :'data-role' => 'property_type_input'
          .error-msg = resource_offer.errors[:"property.property_type"].join(', ')

      .form-group.row.invisible@floor_area
        .col-2
          = ff.label :floor_area, :class => 'col-form-label'
        span.area-field
          = ff.number_field :floor_area, { :value => 0, :in => 0...9999, :class => 'form-control area-input' }
        span.unit m<sup>2</sup>
      .form-group.row.invisible@land_area
        .col-2
          = ff.label :land_area, :class => 'col-form-label'
        span.area-field
          = ff.number_field :land_area, { :value => 0, :in => 0...9999, :class => 'form-control area-input' }
        span.unit m<sup>2</sup>
      .form-group.row
        .col-2
          = ff.label :bedrooms, :class => 'col-form-label'
        .col-1
          = ff.select :bedrooms, ((0..4).map {|i| [i,i] } << ['5+', 5]), {}, :class => 'custom-select'
      .form-group.row
        .col-2
          = ff.label :bathrooms, :class => 'col-form-label'
        .col-1
          = ff.select :bathrooms, ((0..4).map {|i| [i,i] } << ['5+', 5]), {}, :class => 'custom-select'
      .form-group.row
        .col-2
          = ff.label :car_spaces, :class => 'col-form-label'
        .col-1
          = ff.select :car_spaces, ((0..4).map {|i| [i,i] } << ['5+', 5]), {}, :class => 'custom-select'
      .form-group.row.additional-parameters
        .col-2
          = label_tag 'Additional parameters'
        .col-4
          - ::Property::ADDITIONAL_PARAMETERS.each do |parameter|
            = label_tag do
              => ff.check_box parameter.to_sym, {}, true, false
              span = parameter.tr('_', ' ')

      = ff.fields_for :property_gallery do |fff|
        .images.form-group.row@@images_upload
          .col-2
            = fff.label :images, :class => 'col-form-label'
          .col-10
            = fff.file_field :images, :multiple => true, :'data-role' => 'file_field', :class => 'form-control-file'
            .list@list

      - unless current_user
        .h4 Profile
        hr
        = ff.fields_for :user, resource_offer.user do |fff|
          .form-group.row
            .col-2
              = f.label :email, :class => 'col-form-label'
            .col-5
              = fff.text_field :email, :class => 'form-control'
              .error-msg = resource_offer.errors[:'property.user.email'].join(', ')

          .company@@company_fields
            = fff.fields_for :company do |ffff|
              .form-group.row
                .col-2.checkbox
                  = label_tag do
                    => ffff.check_box :abn_confirm, {:checked => resource_offer.property.user.company.abn_confirm == 'true', :'data-role' => 'abn_confirm'}, true, false
                    span I have ABN
                .col-10 If you are listing more than 1 property or are a real estate professional or agent you must provide an ABN.

              .company-fields@company_fields class="#{'invisible' unless resource_offer.property.user.company.abn_confirm == 'true'}"
                .form-group.row
                  .col-2
                    = ffff.label :abn, 'ABN', :class => 'col-form-label'
                  .col-2
                    = ffff.text_field :abn, :maxlength => 11, :class => 'form-control'
                    .error-msg = resource_offer.errors['property.user.company.abn'].join(', ')

                .form-group.row
                  .col-2
                    = ffff.label :name, 'Company name', :class => 'col-form-label'
                  .col-5
                    = ffff.text_field :name, :class => 'form-control'
                    .error-msg = resource_offer.errors['property.user.company.name'].join(', ')

    - if resource_offer.type == 'Sell'
      .h4 Rent offer
      hr
      .rent-fields
        .form-group.row
          .col-2.checkbox
            = label_tag do
              => f.check_box :rent_confirm, {:checked => resource_offer.rent_confirm == 'true', :'data-role' => 'rent_confirm'}, true, false
              span Create rent offer
          .h5.col-10 You can duplicate an offer for rent until your home is sold
        .rent-fields@rent_fields class="#{'invisible' unless resource_offer.rent_confirm == 'true'}"
          .form-group.row
            .col-2
              = f.label :period, :class => 'col-form-label'
            .col-10
              = select_tag 'period', options_for_select(Offer::PERIOD_TYPES), :class => 'custom-select', :'data-role' => 'period_select', :include_blank => "Select #{resource_offer.type.downcase} period"
              = f.hidden_field :rent_period, :'data-role' => 'period_input'
              .error-msg = resource_offer.errors[:rent_period].join(', ')
          .form-group.row
            .col-2
            .col-10
              .invisible@quantity_field
                = number_field_tag 'quantity', 1, :in => 1...13, :class => 'form-control quantity-input', :'data-role' => 'quantity_input'
              .invisible@daterange_field
                = text_field_tag 'daterange', nil, :maxlength => 23, :class => 'daterange-input form-control', :'data-role' => 'daterange_input'

          .form-group.row
            .col-2
              = f.label :rent_price, :class => 'col-form-label'
            .col-10
              = f.text_field :rent_price, :class => 'form-control price-input'
              span.unit AUD
              .error-msg = resource_offer.errors[:rent_price].join(', ')

    .form-group.submit.row
      .col-2
      .col-10
        = f.submit "#{resource_offer.persisted? ? 'Update' : 'Create'}", :class => "btn btn-primary btn-md"

app/views/offers/edit.html.slim
- if resource_offer.user == current_user
  = render 'form'

app/views/offers/index.html.slim
.offers.row
  .col-md-8
    .list-group
      - @offers.each do |offer|
        a.list-group-item.list-group-item-action href="#{offer_path(offer)}"
          .offer.d-flex.flex-row
            - if offer.property_gallery.try(:images).present?
              .offer-image.m-1 style="background-image:url(#{offer.property_gallery.images.first.url(:index_preview)});"
            - else
              / .offer-image.m-1 = image_tag 'default_property_image'
            .offer-info-left.m-1
              .h5 = offer.property.property_type
              p = offer.property.address
              ul.list-group.params
                - if offer.property.try(:bedrooms).try(:positive?)
                  li.list-group-item.justify-content-between
                    | Bedrooms
                    span.badge.badge-default.badge-pill = offer.property.bedrooms
                - if offer.property.try(:bathrooms).try(:positive?)
                  li.list-group-item.justify-content-between
                    | Bathrooms
                    span.badge.badge-default.badge-pill = offer.property.bathrooms
                - if offer.property.try(:car_spaces).try(:positive?)
                  li.list-group-item.justify-content-between
                    | Car spaces
                    span.badge.badge-default.badge-pill = offer.property.car_spaces
              ul.list-group.area
                - if offer.property.try(:floor_area).try(:positive?)
                  li.list-group-item
                    = "Floor area: #{offer.property.floor_area}"
                    span m<sup>2</sup>
                - if offer.property.try(:land_area).try(:positive?)
                  li.list-group-item
                    = "Land area: #{offer.property.land_area}"
                    span m<sup>2</sup>
            .offer-info-right.m-1
              span.badge.badge-info.badge-pill = offer.user.try(:company).try(:abn_valid?) ? 'real estate agent' : 'private property owner'
              - if offer.type == 'Swap'
                p = "#{offer.type}"
              - else
                - if current_user
                  p = "#{offer.type} for"
                  p = number_to_currency(offer.price, :unit => 'AUD', :precision => 0, :delimiter => ',', :format => '%n %u')
                - else
                  p = "#{offer.type}"
              - if offer.with_period?
                p.p-1
                  = "Period: #{offer.period}"

      = will_paginate @Offers
  .col-md-4
    .card
      .card-header Search
      .card-block.search@@search data-country=Rails.application.secrets[:location]['country'] data-region=Rails.application.secrets[:location]['region']
        = form_tag({controller: 'offers', action: 'index'}, method: "get") do
          .type.form-group
            .field-label Type
            .field-input
              = select_tag 'type', options_for_select(::Offer::OFFER_TYPES, params[:type]), :class => 'form-control', :prompt => 'All'
          .address.form-group@address
            .field-input
              = text_field_tag 'address', nil, :placeholder => 'Start typing a address...', :class => 'form-control'
              = hidden_field_tag :latitude, '', :'data-role' => 'gmaps-output-latitude'
              = hidden_field_tag :longitude, '', :'data-role' => 'gmaps-output-longitude'
          - if current_user
            .price-range.form-group
              .price-min
                .field-label Price min
                .field-input
                  = number_field_tag 'min_price', params[:min_price], :min => 1, :class => 'form-control'
              .price-max
                .field-label Price max
                .field-input
                  = number_field_tag 'max_price', params[:max_price], :min => 1, :class => 'form-control'
          .land-area.form-group
            .field-label Minimum Land
            span.area-field
              = number_field_tag 'minimum_land_area', params[:minimum_land_area], { :value => 0, :in => 0...9999, :class => 'form-control area-input' }
            span.unit m<sup>2</sup>
          .property-type.form-group
            .field-input
              .dropdown@property_dropdown
                button.btn.btn-secondary.dropdown-toggle#dropdownMenuButton type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" Select property types
                .dropdown-menu@dropdown_menu aria-labelledby="dropdownMenuButton"
                  .dropdown-item
                    = label_tag do
                      => check_box_tag 'All', '', params[:property_types].blank?, :'data-role' => 'all_property_types'
                      span = 'All'
                  - Property::PROPERTY_TYPES.flatten.reject { |x| x == 'F' || x == 'L' || x == 'LF' }.each do |type|
                    .dropdown-item
                      = label_tag do
                        => check_box_tag 'property_types', type, (params[:property_types].try(:include?, type)), :'data-role' => 'property_type_checkbox'
                        span = type
              = hidden_field_tag :property_types, '', :multiple => true, :'data-role' => 'property_types'
          .additional-parameters.form-group
            .field-input
              .dropdown@property_parameters_dropdown
                button.btn.btn-secondary.dropdown-toggle#dropdownMenuButton type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" Select additional parameters
                .dropdown-menu@dropdown_menu aria-labelledby="dropdownMenuButton"
                  - Property::ADDITIONAL_PARAMETERS.each do |parameter|
                    .dropdown-item
                      = label_tag do
                        => check_box_tag 'additional_parameters', parameter, (params[:additional_parameters].try(:include?, parameter)), :'data-role' => 'additional_parameters_checkbox'
                        span = parameter.tr('_', ' ')
              = hidden_field_tag :additional_parameters, '', :multiple => true, :'data-role' => 'additional_parameters'
          .submit.form-group
            .field-input
              = submit_tag 'Search', :class => 'btn btn-primary'
    - if params[:type].present?
      .card.create-offer
        .card-header Create offer
        .card-block.add-offer
          - if params[:type] == 'Sell'
            .h4 HOW Sell it&nbsp;works for you on&nbsp;Sell it&nbsp;Swap it&nbsp;Buy it
            p Deciding to&nbsp;sell your home privately may seem a&nbsp;little daunting, but more and more people are doing it&nbsp;every day. It&rsquo;s a&nbsp;lot easier than you think, and we&nbsp;are here to&nbsp;assist you to&nbsp;get started to&nbsp;sell your property.
            p Register for free, receive a&nbsp;unique password and use the easy fill listing system to&nbsp;upload your property details, floor plan and photos. We&nbsp;will add a&nbsp;map and your dedicated property promotion page and have your listing up&nbsp;live within the hour.

          - if params[:type] == 'Swap'
            .h4 HOW Swap it&nbsp;works for you on&nbsp;Sell it&nbsp;Swap it&nbsp;Buy it
            p Maybe swapping your home seems a&nbsp;little unusual, but ask yourself: why not just swap my&nbsp;place with someone else&rsquo;s place for a&nbsp;holiday here in&nbsp;Australia or&nbsp;even in&nbsp;another country?
            p Swap it&nbsp;for a&nbsp;holiday, a&nbsp;couple of&nbsp;weeks, a&nbsp;month, a&nbsp;year or&nbsp;maybe, if&nbsp;you want to&nbsp;move permanently, then swap it&nbsp;forever? With no&nbsp;agent&rsquo;s commissions to&nbsp;pay or&nbsp;financial transactions to&nbsp;figure out, just agree and SWAP&nbsp;IT.
            p Register for Free, receive a&nbsp;unique password and use the easy fill listing system to&nbsp;upload your property to&nbsp;swap details, floor plan and photos. We&nbsp;will add a&nbsp;map and your dedicated property swap page and have your listing up&nbsp;live within the hour.

          - if params[:type] == 'Rent'
            .h3 HOW Rent it&nbsp;works for you on&nbsp;Sell it&nbsp;Swap it&nbsp;Buy it
            p Renting out your property privately may seem a&nbsp;different, but why pay agents fees and commissions for something you can easily do&nbsp;yourself and we&rsquo;re here to&nbsp;assist you to&nbsp;get started to&nbsp;rent your property.
            p Register for Free, receive a&nbsp;unique password and use the easy fill listing system to&nbsp;upload your rental property details, floor plan and photos. We&nbsp;will add a&nbsp;map and your dedicated property promotion page and have your listing up&nbsp;live within the hour.
          = link_to "Add my property to #{params[:type]}", new_offer_path(:type => params[:type]), :class => 'btn btn-success'

app/views/offers/new.html.slim
= render 'form'

app/views/offers/show.html.slim
.offer-show.row@@offer_show
  .col-md-12
    .card
      .offer-head
        .header.clearfix
          .h4 = resource_offer.property.property_type
          - if resource_offer.user == current_user
            = link_to 'Edit my offer', edit_offer_path(resource_offer), :class => 'btn btn-primary btn-sm'
          - if resource_offer.property.with_coordinates?
            .h4.float-right = link_to resource_offer.property.address, "https://maps.google.com/maps?q=#{resource_offer.property.latitude},#{resource_offer.property.longitude}", :target => "_blank"
          - else
            .h4.float-right = resource_offer.property.address

      .offer-body
        - if resource_offer.property.property_gallery.try(:images).present?
          .fotorama[
            data-width="100%"
            data-maxwidth="100%"
            data-ratio="16/9"
            data-allowfullscreen="true"
            data-nav="thumbs"
          ]
            - resource_offer.property.property_gallery.images.each do |image|
              = image_tag image.url

        .d-flex.flex-row
          .offer-description
            p = resource_offer.description
          .offer-info
            - if resource_offer.type == 'Swap'
              p = resource_offer.type
            - else
              - if current_user
                p = "#{resource_offer.type} for #{number_to_currency(resource_offer.price, :unit => 'AUD', :precision => 0, :delimiter => ',', :format => '%n %u')}"
              - else
                p = "#{resource_offer.type}"
            - if resource_offer.with_period?
              p = "Period: #{resource_offer.period}"
          - if current_user && current_user != resource_offer.user
            .offer-owner-contact
              button.btn.btn-primary type="button" data-toggle="modal" data-target="#contactModal"
                | Contact with owner

              .modal.fade#contactModal@contact_modal tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-url="#{contact_messages_path}"
                .modal-dialog role="document"
                  .modal-content
                    .modal-header
                      .h5.modal-title#exampleModalLabel Contact with owner
                      button.close type="button" data-dismiss="modal" aria-label="Close"
                        span aria-hidden="true" &times;
                    .modal-body
                      .form-group
                        = text_area_tag 'message', nil, { :class => 'form-control', :'data-role' => 'contact_message', :rows => 5 }
                      .form-group.checkbox
                        = label_tag do
                          => check_box_tag 'approved_financing', 1, false, { :'data-role' => 'approved_financing' }
                          span I have approved financing for deal

                        = hidden_field_tag 'email', value = resource_offer.user.email, { :'data-role' => 'contact_email' }
                        = hidden_field_tag 'sender_id', value = current_user.id, { :'data-role' => 'sender_id' }

                    .modal-footer
                      button.btn.btn-secondary type="button" data-dismiss="modal" Close
                      button.btn.btn-primary type="button" data-role="send_message" Send message
        .d-flex.flex-row
          .property-features
            ul.list-group.params
              - if resource_offer.property.try(:bedrooms).try(:positive?)
                li.list-group-item.justify-content-between
                  | Bedrooms
                  span.badge.badge-default.badge-pill = resource_offer.property.bedrooms
              - if resource_offer.property.try(:bathrooms).try(:positive?)
                li.list-group-item.justify-content-between
                  | Bathrooms
                  span.badge.badge-default.badge-pill = resource_offer.property.bathrooms
              - if resource_offer.property.try(:car_spaces).try(:positive?)
                li.list-group-item.justify-content-between
                  | Car spaces
                  span.badge.badge-default.badge-pill = resource_offer.property.car_spaces
            ul.list-group.area
              - if resource_offer.property.try(:floor_area).try(:positive?)
                li.list-group-item
                  = "Floor area: #{resource_offer.property.floor_area}"
                  span m<sup>2</sup>
              - if resource_offer.property.try(:land_area).try(:positive?)
                li.list-group-item
                  = "Land area: #{resource_offer.property.land_area}"
                  span m<sup>2</sup>
            ul.list-group.additional
              - if resource_offer.property.lounge_room
                li.list-group-item Lounge room
              - if resource_offer.property.kitchen
                li.list-group-item Kitchen
              - if resource_offer.property.dinning_room
                li.list-group-item Dinning room
              - if resource_offer.property.laundry
                li.list-group-item Laundry
              - if resource_offer.property.on_sweet
                li.list-group-item On sweet
              - if resource_offer.property.powder_room
                li.list-group-item Powder room