config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :offers
  resources :sells, :controller => 'offers', :type => 'Sell'
  resources :rents, :controller => 'offers', :type => 'Rent'
  resources :swaps, :controller => 'offers', :type => 'Swap'

  resources :properties
  resources :users

  get '/login', :to => 'user_sessions#new', :as => :new_user_session
  post '/login', :to => 'user_sessions#create', :as => :user_sessions
  get '/logout', :to => 'user_sessions#destroy', :as => :user_session

  get '/disclaimer', :to => 'pages#disclaimer', :as => :disclaimer
  get '/contacts', :to => 'pages#contacts', :as => :contacts
  post '/contacts', :to => 'feedbacks#create', :as => :feedbacks
  post '/message', :to => 'contact_messages#create', :as => :contact_messages
  get '/privacy_policy', :to => 'pages#privacy_policy', :as => :privacy_policy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery :with => :exception
  after_action :prepare_unobtrusive_flash

  helper_method :current_user_session, :current_user

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.slim
hr
.footer.row
  .col-md-4
    - if current_page?(disclaimer_path)
      span.m-2 Disclaimer
    - else
      = link_to 'Disclaimer', disclaimer_path, :class => 'm-2'

    - if current_page?(privacy_policy_path)
      span.m-2 Privacy Policy
    - else
      = link_to 'Privacy Policy', privacy_policy_path, :class => 'm-2'

    - if current_page?(contacts_path)
      span.m-2 Contact us
    - else
      = link_to 'Contact us', contacts_path, :class => 'm-2'
  .col-md-8

app/views/application/_header.html.slim
nav.navbar.navbar-toggleable-md.navbar-light
  button.navbar-toggler.navbar-toggler-right type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon
  .navbar-brand
    .brand-top
      = link_to 'SELL or SWAP or RENT or BUY', root_path, :class => "h4"
    .brand-bottom
      = link_to 'My property by private transaction', root_path, :class => 'h5'
  .collapse.navbar-collapse id="navbarSupportedContent"
    ul.navbar-nav.ml-auto
      - if current_user
        li.nav-item
          = link_to "Edit Profile", edit_user_path(:current), :class => 'btn btn-sm align-right btn-primary'
        li.nav-item
          = link_to "Logout", user_session_path, :class => 'btn btn-sm align-right btn-danger'
      - else
        li.nav-item
          = link_to "Members Login", new_user_session_path, :class => 'btn btn-sm align-right btn-success'
        li.nav-item
          = link_to 'Become a Member', new_user_path, :class => 'btn btn-sm align-right btn-primary'